In [3]:
import os
import random
import functools
import csv
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import evaluate

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix, classification_report, balanced_accuracy_score, accuracy_score

from datasets import Dataset, DatasetDict
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

from huggingface_hub import login

import os 

login(token = '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')

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)


/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /Users/yeji/.cache/huggingface/token
Login successful


In [4]:

df = pd.read_csv("finance_data.csv")
df

labels                                           sentence  \
0     neutral  According to Gran, the company has no plans to...   
1     neutral  Technopolis plans to develop in stages an area...   
2    negative  The international electronic industry company ...   
3    positive  With the new production plant the company woul...   
4    positive  According to the company's updated strategy fo...   
..        ...                                                ...   
494   neutral  In August, Latvijas Finieris ordered all produ...   
495  positive  It delivers a different user experience and en...   
496   neutral  Jacobs has been supporting Storengy's investme...   
497  positive  ADPnews - Jun 30, 2009 - Finnish stainless ste...   
498  positive  Most of the increase in net sales was due to t...   

                                          kor_sentence  
0    Gran에 따르면, 그 회사는 회사가 성장하고 있는 곳이지만, 모든 생산을 러시아로...  
1    테크노폴리스는 컴퓨터 기술과 통신 분야에서 일하는 회사들을 유치하기 위해 10만 평...  
2    국제 전자산업 회사인 엘코텍은 탈린 공장에서 수십 명의 직원을 해고했으며, 이전의 ...  
3    새로운 생산공장으로 인해 회사는 예상되는 수요 증가를 충족시킬 수 있는 능력을 증가...  
4    2009-2012년 회사의 업데이트된 전략에 따르면, Basware는 20% - 4...  
..                                                 ...  
494  8월, 란트비야스 피니에리스는 리투아니아 우크메르게에 새로운 녹색 베니어 공장을 지...  
495  그것은 다른 사용자 경험을 제공하고 우리가 다룰 수 있는 시장을 넓힐 수 있게 해줍...  
496  Jacobs는 소유주 엔지니어로 2006년부터 Storengy의 스토리지 사이트 개...  
497  ADP뉴스 - 2009년 6월 30일 - 핀란드 스테인리스강 제조업체인 Outoku...  
498     순매출 증가의 대부분은 정원공구와 보트를 생산하는 스웨덴 실바를 인수했기 때문이다.  

[499 rows x 3 columns]

In [5]:
df['labels']=df['labels'].astype('category')
df['target']=df['labels'].cat.codes

df.head()

labels                                           sentence  \
0   neutral  According to Gran, the company has no plans to...   
1   neutral  Technopolis plans to develop in stages an area...   
2  negative  The international electronic industry company ...   
3  positive  With the new production plant the company woul...   
4  positive  According to the company's updated strategy fo...   

                                        kor_sentence  target  
0  Gran에 따르면, 그 회사는 회사가 성장하고 있는 곳이지만, 모든 생산을 러시아로...       1  
1  테크노폴리스는 컴퓨터 기술과 통신 분야에서 일하는 회사들을 유치하기 위해 10만 평...       1  
2  국제 전자산업 회사인 엘코텍은 탈린 공장에서 수십 명의 직원을 해고했으며, 이전의 ...       0  
3  새로운 생산공장으로 인해 회사는 예상되는 수요 증가를 충족시킬 수 있는 능력을 증가...       2  
4  2009-2012년 회사의 업데이트된 전략에 따르면, Basware는 20% - 4...       2

In [6]:
df['labels'].cat.categories


Index(['negative', 'neutral', 'positive'], dtype='object')

In [7]:

category_map = {code: category for code, category in enumerate(df['labels'].cat.categories)}

category_map

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [8]:
train_end_point = int(df.shape[0]*0.6)
val_end_point = int(df.shape[0]*0.8)
df_train = df.iloc[:train_end_point,:]
df_val = df.iloc[train_end_point:val_end_point,:]
df_test = df.iloc[val_end_point:,:]
print(df_train.shape, df_test.shape, df_val.shape)

(299, 4) (100, 4) (100, 4)


In [9]:

# Converting pandas DataFrames into Hugging Face Dataset objects:
dataset_train = Dataset.from_pandas(df_train.drop('labels',axis=1))
dataset_val = Dataset.from_pandas(df_val.drop('labels',axis=1))
dataset_test = Dataset.from_pandas(df_test.drop('labels',axis=1))

In [10]:

# Shuffle the training dataset
dataset_train_shuffled = dataset_train.shuffle(seed=42)  # Using a seed for reproducibility

In [11]:

# Combine them into a single DatasetDict
dataset = DatasetDict({
    'train': dataset_train_shuffled,
    'val': dataset_val,
    'test': dataset_test
})
dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'kor_sentence', 'target'],
        num_rows: 299
    })
    val: Dataset({
        features: ['sentence', 'kor_sentence', 'target'],
        num_rows: 100
    })
    test: Dataset({
        features: ['sentence', 'kor_sentence', 'target'],
        num_rows: 100
    })
})

In [12]:

dataset['train']

Dataset({
    features: ['sentence', 'kor_sentence', 'target'],
    num_rows: 299
})

In [13]:
df_train.target.value_counts(normalize=True)


target
2    0.896321
1    0.100334
0    0.003344
Name: proportion, dtype: float64

In [14]:

class_weights=(1/df_train.target.value_counts(normalize=True).sort_index()).tolist()
class_weights=torch.tensor(class_weights)
class_weights=class_weights/class_weights.sum()
class_weights

tensor([0.9643, 0.0321, 0.0036])

In [15]:
model_name = "meta-llama/Meta-Llama-3-8B"


In [16]:

quantization_config = BitsAndBytesConfig(
    load_in_4bit = True, # enable 4-bit quantization
    bnb_4bit_quant_type = 'nf4', # information theoretically optimal dtype for normally distributed weights
    bnb_4bit_use_double_quant = True, # quantize quantized weights //insert xzibit meme
    bnb_4bit_compute_dtype = torch.bfloat16 # optimized fp format for ML
)


In [17]:

lora_config = LoraConfig(
    r = 16, # the dimension of the low-rank matrices
    lora_alpha = 8, # scaling factor for LoRA activations vs pre-trained weight activations
    target_modules = ['q_proj', 'k_proj', 'v_proj', 'o_proj'],
    lora_dropout = 0.05, # dropout probability of the LoRA layers
    bias = 'none', # wether to train bias weights, set to 'none' for attention layers
    task_type = 'SEQ_CLS'
)

In [18]:
device = torch.device("mps")

In [19]:
os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO'] = '0.0'

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    #quantization_config=quantization_config,
    #device_map="mps",
    torch_dtype=torch.float16,
    num_labels=3
)

model.to("mps")
     

Loading checkpoint shards: 100%|██████████| 4/4 [00:15<00:00,  3.98s/it]
Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


LlamaForSequenceClassification(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
 

In [20]:
model = get_peft_model(model, lora_config)
model


Could not load bitsandbytes native library: dlopen(/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cpu.dylib, 0x0006): tried: '/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cpu.dylib' (no such file), '/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cpu.dylib' (no such file)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 109, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 96, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): LlamaForSequenceClassification(
      (model): LlamaModel(
        (embed_tokens): Embedding(128256, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaSdpaAttention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (k_proj): lora.Linear(
                (bas

In [21]:

tokenizer = AutoTokenizer.from_pretrained(model_name, add_prefix_space=True)

tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.pad_token = tokenizer.eos_token

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [22]:

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

In [23]:
sentences = df_test.sentence.tolist()
sentences[0:2]

['Lemminkainen Oyj said that it has signed credit agreements with Nordea Bank STO : NDA, Pohjola Bank HEL : POH1S, Sampo Bank HEL : SAMAS and Svenska Handelsbanken STO : SHB A.',
 'Pohjola could increase its stake to 45 % in 2013.']

In [24]:
os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO'] = '0.0'

# Convert summaries to a list
sentences = df_test.sentence.tolist()

# Define the batch size
batch_size = 32  # You can adjust this based on your system's memory capacity

# Initialize an empty list to store the model outputs
all_outputs = []

# Process the sentences in batches
for i in range(0, len(sentences), batch_size):
    # Get the batch of sentences
    batch_sentences = sentences[i:i + batch_size]

    # Tokenize the batch
    inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Move tensors to the device where the model is (e.g., GPU or CPU)
    
    #inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}
    #inputs = {k: v.to('mps' if torch.backends.mps.is_available() else 'cpu') for k, v in inputs.items()}
    device = 'mps' if torch.backends.mps.is_available() else 'cpu'
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # Perform inference and store the logits
    with torch.no_grad():
        #outputs = model.to(**inputs)
        outputs = model(**inputs)
        all_outputs.append(outputs['logits'])

In [25]:

final_outputs = torch.cat(all_outputs, dim=0)
final_outputs

tensor([[ 0.6509, -0.9473, -2.3750],
        [ 4.1680, -1.6211, -2.9375],
        [ 0.1738, -2.8809,  1.8604],
        [ 2.3516, -2.4668, -1.1201],
        [ 1.6113, -2.0957, -0.4724],
        [ 2.8984, -0.5962,  0.9126],
        [ 2.9277, -0.3154, -1.1885],
        [ 3.9121,  1.1055, -2.0527],
        [ 5.0820, -1.0605, -2.1992],
        [ 2.4922, -0.9614, -2.6367],
        [ 2.2617, -0.6997,  1.4941],
        [ 1.3232,  2.8262, -2.8047],
        [ 2.2695,  0.9326, -0.8477],
        [ 3.4688,  0.6050,  4.2383],
        [ 5.5078,  1.2305, -2.9023],
        [ 0.7168,  1.4990, -2.3848],
        [ 3.6230, -4.5273,  0.7285],
        [ 2.8965,  1.6641, -0.8125],
        [ 2.1250, -0.1031, -1.1494],
        [ 3.8418, -2.1113,  1.1719],
        [ 0.3206, -3.1758, -2.8184],
        [ 4.3086, -2.5469, -1.4219],
        [ 3.5098, -0.4622, -0.0425],
        [ 3.4336, -0.7734, -0.3809],
        [ 3.4570, -0.8608, -0.1360],
        [ 0.8315, -2.0391,  0.3950],
        [ 1.0078, -4.6758,  0.9785],
 

In [26]:
final_outputs.argmax(axis=1)


tensor([0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0,
        0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 2], device='mps:0')

In [27]:

df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()
df_test['predictions']

/var/folders/91/lyd666dn05368kh248wtmtdh0000gn/T/ipykernel_29564/1309614195.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()


399    0
400    0
401    2
402    0
403    0
      ..
494    0
495    0
496    1
497    0
498    2
Name: predictions, Length: 100, dtype: int64

In [28]:
df_test['predictions'].value_counts()


predictions
0    79
2    17
1     4
Name: count, dtype: int64

In [29]:
df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])
df_test['predictions']

/var/folders/91/lyd666dn05368kh248wtmtdh0000gn/T/ipykernel_29564/4293232383.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])


399    negative
400    negative
401    positive
402    negative
403    negative
         ...   
494    negative
495    negative
496     neutral
497    negative
498    positive
Name: predictions, Length: 100, dtype: object

In [32]:
def get_performance_metrics(df_test):
  y_test = df_test.labels
  y_pred = df_test.predictions

  print("Confusion Matrix:")
  print(confusion_matrix(y_test, y_pred))

  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))

  print("Balanced Accuracy Score:", balanced_accuracy_score(y_test, y_pred))
  print("Accuracy Score:", accuracy_score(y_test, y_pred))
     

In [33]:
get_performance_metrics(df_test)


Confusion Matrix:
[[ 3  0  0]
 [52  4  6]
 [24  0 11]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.04      1.00      0.07         3
     neutral       1.00      0.06      0.12        62
    positive       0.65      0.31      0.42        35

    accuracy                           0.18       100
   macro avg       0.56      0.46      0.21       100
weighted avg       0.85      0.18      0.23       100

Balanced Accuracy Score: 0.4596006144393241
Accuracy Score: 0.18


In [34]:

MAX_LEN = 512
col_to_delete = ['sentence']

def llama_preprocessing_function(examples):
    return tokenizer(examples['sentence'], truncation=True, max_length=MAX_LEN)

tokenized_datasets = dataset.map(llama_preprocessing_function, batched=True, remove_columns=col_to_delete)
tokenized_datasets = tokenized_datasets.rename_column("target", "labels")
tokenized_datasets.set_format("torch")

Map: 100%|██████████| 100/100 [00:00<00:00, 26240.64 examples/s]


In [35]:
collate_fn = DataCollatorWithPadding(tokenizer=tokenizer)


In [36]:

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {'balanced_accuracy' : balanced_accuracy_score(predictions, labels),'accuracy':accuracy_score(predictions,labels)}


In [37]:
class CustomTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        # Ensure label_weights is a tensor
        if class_weights is not None:
            self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)
        else:
            self.class_weights = None

    def compute_loss(self, model, inputs, return_outputs=False):
        # Extract labels and convert them to long type for cross_entropy
        labels = inputs.pop("labels").long()

        # Forward pass
        outputs = model(**inputs)

        # Extract logits assuming they are directly outputted by the model
        logits = outputs.get('logits')

        # Compute custom loss with class weights for imbalanced data handling
        if self.class_weights is not None:
            loss = F.cross_entropy(logits, labels, weight=self.class_weights)
        else:
            loss = F.cross_entropy(logits, labels)

        return (loss, outputs) if return_outputs else loss

In [38]:
training_args = TrainingArguments(
    output_dir = 'sentiment_classification',
    learning_rate = 1e-4,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size = 8,
    num_train_epochs = 2,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True
)

/opt/anaconda3/envs/mlflow-venv/lib/python3.12/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [39]:

trainer = CustomTrainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_datasets['train'],
    eval_dataset = tokenized_datasets['val'],
    tokenizer = tokenizer,
    data_collator = collate_fn,
    compute_metrics = compute_metrics,
    class_weights=class_weights,
)

/var/folders/91/lyd666dn05368kh248wtmtdh0000gn/T/ipykernel_29564/2851958097.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)


In [40]:
import mlflow


os.environ['MLFLOW_S3_ENDPOINT_URL'] = 'http://localhost:9000'
os.environ['AWS_ACCESS_KEY_ID'] = 'minioadmin'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'minioadmin'
os.environ['MLFLOW_TRACKING_URI'] = 'http://localhost:5001'

EXPERIMENT_NAME = "test_240629_02"
mlflow.set_experiment(EXPERIMENT_NAME)


2024/07/07 06:53:44 INFO mlflow.tracking.fluent: Experiment with name 'test_240629_02' does not exist. Creating a new experiment.


<Experiment: artifact_location='mlflow-artifacts:/1', creation_time=1720302824525, experiment_id='1', last_update_time=1720302824525, lifecycle_stage='active', name='test_240629_02', tags={}>

In [43]:
with mlflow.start_run() as run:
    model.to('mps')
   #mlflow.transformers.log_model(transformers_model=model, artifact_path="my_pipeline")
    #mlflow.log_artifact('Dockerfile', artifact_path='my_pipeline')
    train_result = trainer.train()

  0%|          | 0/76 [05:10<?, ?it/s]


RuntimeError: Placeholder storage has not been allocated on MPS device!